name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file TestingScripts/Dockerfile --tag docker.pkg.github.com/raesene/dockerized-security-tools/testingscripts
    - name: login to the gh docker repo
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: push to gh docker repo
      run: docker push docker.pkg.github.com/raesene/dockerized-security-tools/testingscripts

