name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file TestingScripts/Dockerfile --tag docker.pkg.github.com/raesene/dockerized-security-tools/testingscripts
    - name: login to the gh docker repo
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: docker login -u raesene -p $GITHUB_TOKEN
    - name: push to gh docker repo
      run: docker push docker.pkg.github.com/raesene/dockerized-security-tools/testingscripts

